### ISSUE TITLE
BUG ・ `notes.db` creates in the working directory

### ISSUE THREAD

**Issue by SwiftDust** [ThatFrogDev/notaben#13]
## Are you facing this issue using Notabena CLI or Desktop?
[ ] CLI
_(as of now, only possible answer)_

## On what platform are you facing the bug?
[ ] Windows 10 or later
[ ] Other Windows
[ ] macOS
[ ] Ubuntu
[ ] Other Linux

## Describe the bug:
The `notes.db` file creates in the folder you run it in, instead of in a general AppData directory or similar.

## How to reproduce the error?
1. Run `cargo r` or `notabena` in any directory
2. Exit the program and see the `ls output` It shows a `notes.db` file.
3. `cd` into another directory
4. Reproduce steps 1 and 2

## Expected behavior
It should create the database file in a general data directory, like `AppData/notabena` or `.notabena`

## Screenshots
_(not required)_ Could you send any screenshots to help us understand and reproduce the error?

## Anything to add?
**Note from the developer:** We didn't design the code for this correctly, but we only realized now. We know how to fix the bug and we're going to patch it as soon as possible.

**Comment by MrSerge01** [comment]
#18
