### ISSUE TITLE
FRQ ・ Return key

### ISSUE THREAD

**Issue by SwiftDust** [ThatFrogDev/notaben#16]
### Is this a fix to a problem or just a new feature that you'd like to see?

Problem

### For what problem is your feature a fix?

If you accidentally clicked on the New note entry for example, you first have to make a note to return.

### What is the solution or feature?

With the introduction of the Return key, you can return to the main menu at any moment.

**Comment by SwiftDust** [comment]
We don't know yet how to fix this, any help (in the form of a pull request or comment) is much appreciated!

**Comment by lilafian** [comment]
do something like ctrl-q to fix it (i would help but idk rust 😭)

**Comment by SwiftDust** [comment]
> do something like ctrl-q to fix it (i would help but idk rust 😭)

`Alt`-`Q` it is 🤠

**Comment by MrSerge01** [comment]
> do something like ctrl-q to fix it (i would help but idk rust 😭)

either ctrl + q or alt + q

**Comment by MrSerge01** [comment]
\+ we found a way, were implementing this

**Comment by SwiftDust** [comment]
Couldn't be bothered doing this for now since we're probably moving away from the current codebase. Will possibly be re-opened when we know more. (https://discord.com/channels/1178803368806842408/1178813526958162001/1179414477175799909 for more information)

**Comment by SwiftDust** [comment]
This is planned.
