### ISSUE TITLE
Write unit tests

### ISSUE THREAD

**Issue by SwiftDust** [ThatFrogDev/notaben#17]
We need to write unit tests so the `rc` branch stays clean and without errors.

**Comment by SwiftDust** [comment]
**Note:** When this gets implemented you don't have to run them yourself, the CI will check if all functions work fine in your code

**Comment by ThatFrogDev** [comment]
Couldn't be bothered doing this for now since we're _probably_ moving away from the current codebase. Will possibly be re-opened when we know more.

**Comment by ThatFrogDev** [comment]
Couldn't be bothered doing this for now since we're probably moving away from the current codebase. Will possibly be re-opened when we know more.

**Comment by SwiftDust** [comment]
Couldn't be bothered doing this for now since we're probably moving away from the current codebase. Will possibly be re-opened when we know more.

**Comment by SwiftDust** [comment]
This is now planned for v0.1.1. Stay tuned! ✌️
