### ISSUE TITLE
FRQ ・ Pack notabena with glibc

### ISSUE THREAD

**Issue by ghost** [ThatFrogDev/notaben#24]
### Is this a fix to a problem or just a new feature that you'd like to see?

Problem

### For what problem is your feature a fix?

The app requires `glibc` to run, a library that's very hard (and non-recommended) to update, making some users (like me) unable to run the executable.

### What is the solution or feature?

Bundling `glibc` onto the executable may be the solution for this.

**Comment by SwiftDust** [comment]
Next release will have a fix for this! Join our Discord for more information, see README.md.
