### ISSUE TITLE
FRQ・You can't edit any note

### ISSUE THREAD

**Issue by numbereddev** [ThatFrogDev/notaben#38]
### Before you start, first check the following:

- [X] I have searched the issues and confirmed that this is not a duplicate or a known issue.
- [X] I am on the newest version of Notabena.

### Are you facing this issue using Notabena CLI or Desktop?

CLI

### What platform are you using Notabena on?

Windows 10 or newer

### What kind of bug are you facing?

When I create a note and try to edit it, after doing it it doesn't save it.

### How to reproduce the bug?

1. Open notabena
2. Create a note or use an existing one if given
3. Try to edit it
4. View it again
5. Not saved

Or alternatively watch this video:

https://github.com/ThatFrogDev/notabena/assets/72300200/6b3b45cf-9f84-44e4-9714-85c60aa1e169

### What did you expect that would happen?

It should have saved the edits.

### Can you send us some screenshots?

See video in `How to reproduce the bug`.

**Comment by SwiftDust** [comment]
Alright, seems like ~~Serge~~ we forgot to add a call to the edit notes function... dang 🥲 we'll patch this as soon as possible. If you want, you (this means: the community) can help us fix this as well! Just send a pull request (be sure to format your code with `cargo fmt`) and we might add this patch in the next release. You'll be rewarded with a contributor role in the Discord, too.

**Comment by SwiftDust** [comment]
Finally did some bug bashing 🐛

**Comment by SwiftDust** [comment]
CAUTION: When this still not works for you, this means your database file is corrupted. Please delete the file `notes.db` or manually solve errors. This can be found in your OSes config directory: `$XDG_CONFIG_HOME/Notabena` for Linux, `~/Library/Application Support/Notabena` for Mac or `%APPDATA%/Notabena` for Windows.
